[package]
name = "freevpn-spawner"
version = "0.1.0"
authors = ["Simon Königsreiter <simon.koenigsreiter@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.15"
scraper = "0.10.0"
subprocess = "0.1.18"
clap = "2.33.0"
ctrlc = { version = "3.0", features = ["termination"] }